os: linux
language: "minimal"
services:
  - docker

jobs:
  include:
    - name: "checks"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` rusdevops/bootstrap-cpp ./scripts/checks.sh


notifications:
  email: false
